# Generated by Django 2.0 on 2017-12-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('said_by', models.CharField(max_length=100)),
                ('quote', models.TextField()),
            ],
        ),
    ]
